### ISSUE TITLE
ui: design

### ISSUE THREAD

**Issue by magiruuvelvet** [magiruuvelvet/QAPI-IDE#3]
Think about how the user interface should look like and what features it should have. The interface should not try to mimic Postman or Insomnia if possible - personally I find their UI design choices a bit clumsy (*coughs in web design on the desktop*). While the idea of tabs is nice, constantly needing to "save" the most trivial changes in that tab is not very nice to work with. I want to avoid tabs entirely and instead switch between several views which belongs to the corresponding request. This also means no multiple requests can be open at the same time.

Features I want to have in the UI module:

 - [ ] ~~projects (save to files / load from files)~~
 - [ ] ~~workspaces (inside a project, should act as a "request group")~~\
       a workspace is now the project which holds request groups... (the name "project" didn't fit very well)
 - [ ] request groups
 - [ ] requests (a ~~workspace~~ request group can have multiple requests)
 - [ ] request folders
 - [ ] credentials store for non-production data to test API auth (plain text) **\***

These are early design ideas which might change.

\* I don't support the idea to use this application to "debug in production".

**Comment by magiruuvelvet** [comment]
## Tasks

- [ ] **menu bar**, what should go there?
- [ ] **workbench layout** (requests, request view, request and response editor, ...)

...
