### ISSUE TITLE
scripting

### ISSUE THREAD

**Issue by magiruuvelvet** [magiruuvelvet/QAPI-IDE#4]
Postman has the possibility to add scripts (in JavaScript) for requests. This would be a nice to have for this application too. I've got some very early stage experimental script running working, but without integration yet (binding native functions, variables, etc.).

Keep an eye on that.

**Comment by magiruuvelvet** [comment]
## Tasks

- [x] C++ support using [cling](https://root.cern.ch/cling), because why not?
- [x] JavaScript support using [duktape](https://duktape.org/) with additional glue code

### C++

- [x] static value binding
- [ ] read/write variable binding
- [ ] function binding
- [ ] function binding with arguments
- [ ] global output redirection (stdout, stderr)
- [ ] cling compiler error redirection (string instead of console)
- [ ] precompiled header cache (generated at runtime for portability reasons)

### JavaScript
- [x] static value binding
- [ ] read/write variable binding
- [ ] function binding
- [ ] function binding with arguments
- [x] ~~global output redirection (stdout, stderr)~~ not needed, implemented basic `console` object
- [ ] duktape(-cpp) error redirection (string instead of console)
